apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipeline-run
spec:
  pipelineSpec:
    tasks:
      - name: npm-install
        taskRef:
          name: npm
      - name: jasmine-tests
        taskRef:
          name: jasmine
        runAfter:
          - npm-install
  params:
    - name: repo-url
      value: https://github.com/your-username/tax-calculator
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: tekton-workspace
